# Generated by Django 5.1.1 on 2024-11-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['precio'], 'permissions': (('visualizar_catalogo', 'Permite a un usuario visualizar el catálogo de vehículos'),), 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
    ]
